FROM websphere-liberty:javaee7

COPY --chown=1001:0 server.xml /config/server.xml
COPY --chown=1001:0 resources/data /opt/ibm/wlp/usr/shared/resources/data
COPY --chown=1001:0 resources/DerbyLibs /opt/ibm/wlp/usr/shared/resources/DerbyLibs
COPY --chown=1001:0 daytrader-ee7-1.0-SNAPSHOT.ear /config/apps

RUN configure.sh



